### Husk disse HTTP endpoints test tar udgangspunkt i din rigtige database

GET http://localhost:8080/dat3_person/api/person/4

###
POST http://localhost:8080/dat3_person/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "Victor", "lastName": "Kalle", "phoneNumber": "7654908",
  "street": "Nørrebros runddel", "zip": "2400", "city": "Nørrebro"}


###
GET http://localhost:8080/dat3_person/api/person/getAll

###
POST http://localhost:8080/dat3_person/api/person
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "maru", "lastName": "huraa", "phoneNumber": "111111"}


###


PUT http://localhost:8080/dat3_person/api/person/6
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"firstName": "Pernille", "lastName": "Herman", "phoneNumber": "77665544"}

###
DELETE http://localhost:8080/dat3_person/api/person/9

